version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mds_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: mds_db
      MYSQL_USER: db-user
      MYSQL_PASSWORD: User@123
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mds_phpmyadmin_container
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Root@123
    ports:
      - "8080:80"

volumes:
  mysql_data:
